# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{apify}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Henning Koch"]
  s.date = %q{2010-08-28}
  s.description = %q{Compact definition of JSON APIs for Rails applications. }
  s.email = %q{github@makandra.de}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = %q{http://github.com/makandra/apify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Compact definition of JSON APIs for Rails applications.}
  s.test_files = [
    "spec/apify/action_spec.rb",
     "spec/apify/client_spec.rb",
     "spec/spec_helper.rb",
     "spec/app_root/app/controllers/api_controller.rb",
     "spec/app_root/app/controllers/application_controller.rb",
     "spec/app_root/app/models/api.rb",
     "spec/app_root/lib/console_with_fixtures.rb",
     "spec/app_root/config/environments/in_memory.rb",
     "spec/app_root/config/environments/mysql.rb",
     "spec/app_root/config/environments/postgresql.rb",
     "spec/app_root/config/environments/sqlite.rb",
     "spec/app_root/config/environments/sqlite3.rb",
     "spec/app_root/config/boot.rb",
     "spec/app_root/config/environment.rb",
     "spec/app_root/config/routes.rb",
     "spec/controllers/api_controller_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

